name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Runnins commands on runner machine
      run: |
        echo "hello"
        ls -al
        pwd
        touch hello.txt
